services:
  flask:
    profiles: ["prod"]
    restart: always
    build: .
    working_dir: /src
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    networks:
      - proxy-network

  flask-dev:
    profiles: ["dev"]
    restart: always
    build: .
    working_dir: /src
    volumes:
      - ./src/:/src/
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - PORT=3001
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
