version: '3.9'
services:
  flask:
    container_name: flask
    command: python3 -m flask run --host=0.0.0.0 -p 80
    restart: always
    build:
      context: ./diasekovaltchukadv/
      dockerfile: Dockerfile
      target: 'develop-stage'
    volumes:
      - './diasekovaltchukadv/src/:/diasekovaltchukadv/src/'
    ports:
      - '80:80'