services:
  diasekovaltchuk:
    profiles: ["prod"]
    container_name: diasekovaltchuk
    restart: unless-stopped
    build: .
    working_dir: /src
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    networks:
      - proxy-network

  diasekovaltchuk-dev:
    profiles: ["dev"]
    container_name: diasekovaltchuk-dev
    restart: unless-stopped
    build: .
    working_dir: /src
    volumes:
      - ./src/:/src/
    ports:
      - "127.0.0.1:3003:3003"
    environment:
      - PORT=3003
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
