# docker-compose.yml

services:
  flask:
    container_name: flask
    restart: always
    build:
      context: ./diasekovaltchukadv/
      dockerfile: Dockerfile
    working_dir: /diasekovaltchukadv/src
    command: python3 main.py
    volumes:
      - './diasekovaltchukadv/src/:/diasekovaltchukadv/src/'
    ports:
      - '80:5000'
    env_file:
      - .env
